### ISSUE TITLE
Signing libraries

### ISSUE THREAD

**Issue by mfw78** [cowdao-grants/cow-shed#12]
https://github.com/meetmangukiya/cow-shed/blob/d67e97dd501d2fec42ab7d3e511bc3f9a2d87a8a/src/LibAuthenticatedHooks.sol#L30-L64

Given that we're already importing OpenZeppelin, is there any substantial reason why not to use their SignatureChecker?

**Comment by meetmangukiya** [comment]
its mostly about reducing memory expansion
